#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>

/*
 * Process states
 */
enum
{
    RUNNING,
    PAUSED
};

/*
 * Global variables modified by signal handlers.
 *
 * volatile sig_atomic_t is safe to modify from
 * signal handlers.
 */
volatile sig_atomic_t current_state = RUNNING;
volatile sig_atomic_t running = 1;

volatile sig_atomic_t usr1_received = 0;
volatile sig_atomic_t usr2_received = 0;
volatile sig_atomic_t int_received = 0;
volatile sig_atomic_t term_received = 0;

/*
 * SIGUSR1 handler
 *
 * Pause the process.
 */
void handle_sigusr1(int signal_number)
{
    (void)signal_number;

    current_state = PAUSED;
    usr1_received = 1;
}

/*
 * SIGUSR2 handler
 *
 * Resume the process.
 */
void handle_sigusr2(int signal_number)
{
    (void)signal_number;

    current_state = RUNNING;
    usr2_received = 1;
}

/*
 * SIGINT handler
 *
 * Ctrl+C should NOT terminate the process.
 */
void handle_sigint(int signal_number)
{
    (void)signal_number;

    int_received = 1;
}

/*
 * SIGTERM handler
 *
 * Terminate the main loop gracefully.
 */
void handle_sigterm(int signal_number)
{
    (void)signal_number;

    running = 0;
    term_received = 1;
}

int main()
{
    /*
     * Register signal handlers using signal().
     */
    if (signal(SIGUSR1, handle_sigusr1) == SIG_ERR)
    {
        perror("Unable to register SIGUSR1");
        return 1;
    }

    if (signal(SIGUSR2, handle_sigusr2) == SIG_ERR)
    {
        perror("Unable to register SIGUSR2");
        return 1;
    }

    if (signal(SIGINT, handle_sigint) == SIG_ERR)
    {
        perror("Unable to register SIGINT");
        return 1;
    }

    if (signal(SIGTERM, handle_sigterm) == SIG_ERR)
    {
        perror("Unable to register SIGTERM");
        return 1;
    }

    /*
     * Display PID.
     */
    printf("Program started\n");
    printf("PID : %d\n", getpid());

    /*
     * Main process loop.
     */
    while (running)
    {
        /*
         * Display messages generated by
         * signal handlers.
         */
        if (usr1_received)
        {
            printf("SIGUSR1 received\n");
            printf("Process paused\n");

            usr1_received = 0;
        }

        if (usr2_received)
        {
            printf("SIGUSR2 received\n");
            printf("Process resumed\n");

            usr2_received = 0;
        }

        if (int_received)
        {
            printf("SIGINT received - process continues running\n");

            int_received = 0;
        }

        if (term_received)
        {
            printf("SIGTERM received\n");
            printf("Terminating gracefully ...\n");

            term_received = 0;
        }

        /*
         * Display current state.
         */
        if (current_state == RUNNING)
        {
            printf("State : RUNNING\n");
        }
        else
        {
            printf("State : PAUSED\n");
        }

        fflush(stdout);

        /*
         * Main activity occurs once every second.
         */
        sleep(1);
    }

    printf("Program exited\n");

    return 0;
}
